name: Container Scan 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Veracode Static Pipeline Scanner
        run: |
          pwd
          export VERACODE_API_KEY_ID=$VERACODE_API_KEY_ID
          export VERACODE_API_KEY_SECRET=$VERACODE_API_KEY_SECRET
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode configure
          ./veracode scan --source ./ --type directory --format json --output veracode_container_scan.json
          ./veracode sbom --source ./ --type directory --format json > sbom.json

      - name: Publish veracode_container_scan.json Artifact
        uses: actions/upload-artifact@v2
        with:
          name: veracode_container_scan.json
          path: ./veracode_container_scan.json

      - name: Publish Veracode sbom.json Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom.json
          path: ./sbom.json